server:
  port: 8083

spring:
  application:
    name: sale-service

  datasource:
    url: jdbc:mysql://localhost:3309/pos_sale_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${SALE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    consul:
      host: localhost
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always